export type TopicGroup = {
  category: string;
  terms: string[];
};

export const TOPIC_TAXONOMY: TopicGroup[] = [
  {
    category: "Artificial Intelligence",
    terms: [
      "Explainable AI",
      "Responsible AI",
      "Trustworthy AI",
      "AI Decision Systems",
      "Cognitive AI",
      "Hybrid AI",
      "Symbolic AI",
      "Autonomous AI Systems",
      "Agentic AI",
      "Multi-Agent Systems",
      "Knowledge Representation",
      "Expert Systems",
    ],
  },
  {
    category: "Deep Learning",
    terms: [
      "Deep Neural Networks",
      "Convolutional Neural Networks (CNN)",
      "Recurrent Neural Networks (RNN)",
      "LSTM",
      "GRU",
      "Transformers",
      "Vision Transformer",
      "Attention Mechanisms",
      "Diffusion Models",
      "GANs",
      "Autoencoders",
      "Variational Autoencoders",
      "Capsule Networks",
      "Self-Supervised Learning",
      "Representation Learning",
    ],
  },
  {
    category: "Neural Networks",
    terms: [
      "Perceptron",
      "Feedforward Networks",
      "Multilayer Perceptron",
      "Hopfield Networks",
      "Radial Basis Networks",
      "Spiking Neural Networks",
      "Graph Neural Networks (GNN)",
    ],
  },
  {
    category: "Generative AI",
    terms: [
      "Large Language Models (LLMs)",
      "Vision-Language Models",
      "Multimodal AI",
      "Foundation Models",
      "Text Generation",
      "Image Generation",
      "Video Generation",
      "Audio Generation",
      "Code Generation",
      "AI Assistants",
      "Conversational AI",
    ],
  },
  {
    category: "Robotics",
    terms: [
      "Robot Learning",
      "Autonomous Robotics",
      "Robotic Manipulation",
      "Industrial Robotics",
      "Collaborative Robots (Cobots)",
      "Mobile Robots",
      "Service Robots",
      "Humanoid Robots",
      "Swarm Robotics",
      "Robot Navigation",
      "Robot Localization",
      "Robot Path Planning",
      "Motion Planning",
      "Robot Vision",
      "SLAM",
      "Learning from Demonstration",
      "Reinforcement Learning for Robots",
      "Human-Robot Interaction",
      "Robot Operating System (ROS)",
    ],
  },
  {
    category: "Autonomous Vehicles",
    terms: [
      "Self-Driving Cars",
      "Autonomous Navigation",
      "Route Planning",
      "Localization",
      "Decision Making",
      "Motion Prediction",
      "Sensor Fusion",
      "LiDAR",
      "Radar Perception",
      "Autonomous Trucks",
      "Robotaxis",
      "Vehicle Trajectory Prediction",
    ],
  },
  {
    category: "ADAS",
    terms: [
      "Lane Detection",
      "Lane Keeping Assist",
      "Object Detection",
      "Pedestrian Detection",
      "Driver Monitoring",
      "Collision Avoidance",
      "Adaptive Cruise Control",
      "Automatic Emergency Braking",
      "Autonomous Parking",
      "Traffic Sign Recognition",
      "Traffic Light Detection",
      "Blind Spot Detection",
      "Night Vision",
    ],
  },
  {
    category: "Internet of Vehicles (IoV)",
    terms: [
      "V2V Communication",
      "V2I Communication",
      "V2X",
      "Connected Vehicles",
      "Cooperative Driving",
      "Fleet Management",
      "Intelligent Traffic Systems",
    ],
  },
  {
    category: "Computer Vision",
    terms: [
      "Image Classification",
      "Semantic Segmentation",
      "Instance Segmentation",
      "Face Recognition",
      "OCR",
      "Pose Estimation",
      "Depth Estimation",
      "Video Analytics",
      "Action Recognition",
      "Scene Understanding",
      "Medical Image Analysis",
      "Image Captioning",
    ],
  },
  {
    category: "Natural Language Processing",
    terms: [
      "Language Models",
      "Text Classification",
      "Machine Translation",
      "Speech Recognition",
      "Sentiment Analysis",
      "Question Answering",
      "Named Entity Recognition",
      "Summarization",
      "Chatbots",
    ],
  },
  {
    category: "Reinforcement Learning",
    terms: [
      "Q-Learning",
      "Deep Q Networks",
      "Policy Gradient",
      "PPO",
      "A3C",
      "SAC",
      "DDPG",
      "TD3",
      "Multi-Agent RL",
      "Continuous Control",
      "Game AI",
    ],
  },
  {
    category: "Edge AI",
    terms: [
      "TinyML",
      "Edge Computing",
      "Embedded AI",
      "FPGA AI",
      "Microcontroller ML",
      "Real-Time Inference",
      "Edge Robotics",
      "Distributed Intelligence",
    ],
  },
  {
    category: "Industry 4.0 & Digital Twins",
    terms: [
      "Smart Manufacturing",
      "Quality Inspection",
      "Predictive Maintenance",
      "Production Optimization",
      "Industrial Digital Twins",
      "Vehicle Digital Twins",
      "Healthcare Digital Twins",
      "Predictive Simulation",
      "Cyber-Physical Systems",
    ],
  },
  {
    category: "IoT & Embedded Systems",
    terms: [
      "Smart Homes",
      "Smart Cities",
      "Sensor Analytics",
      "IoT Security",
      "Smart Agriculture",
      "Smart Grid",
      "Embedded Linux",
      "RTOS",
      "ARM Processors",
      "Digital Signal Processing",
    ],
  },
  {
    category: "Wireless Communication",
    terms: [
      "5G Optimization",
      "6G",
      "Beamforming",
      "Resource Allocation",
      "Cognitive Radio",
      "Wireless Security",
      "Satellite Communication",
      "Satellite Navigation",
    ],
  },
  {
    category: "Human-Computer Interaction",
    terms: [
      "Gesture Recognition",
      "Emotion Recognition",
      "Eye Tracking",
      "Brain-Computer Interface",
      "Adaptive Interfaces",
      "Human-Machine Collaboration",
    ],
  },
  {
    category: "Cloud AI & MLOps",
    terms: [
      "Federated Learning",
      "Model Deployment",
      "Model Monitoring",
      "CI/CD for ML",
      "AutoML",
      "Feature Store",
      "Data Pipelines",
    ],
  },
  {
    category: "Data Science",
    terms: [
      "Predictive Analytics",
      "Time Series Forecasting",
      "Feature Engineering",
      "Clustering",
      "Recommendation Systems",
      "Dimensionality Reduction",
      "Big Data",
    ],
  },
  {
    category: "Healthcare",
    terms: [
      "Disease Prediction",
      "Medical Imaging",
      "Drug Discovery",
      "Clinical Decision Support",
      "ECG Analysis",
      "EEG Analysis",
      "Cancer Detection",
      "Wearable AI",
    ],
  },
  {
    category: "Cybersecurity",
    terms: [
      "Intrusion Detection",
      "Malware Detection",
      "Phishing Detection",
      "Fraud Detection",
      "Anomaly Detection",
      "Threat Intelligence",
    ],
  },
  {
    category: "Emerging AI Research",
    terms: [
      "Explainable AI",
      "Causal Machine Learning",
      "Neuro-Symbolic AI",
      "Continual Learning",
      "Meta Learning",
      "Few-Shot Learning",
      "Zero-Shot Learning",
      "Transfer Learning",
      "Multi-Task Learning",
      "Weakly Supervised Learning",
      "Embodied AI",
      "Physical AI",
    ],
  },
];
